### ISSUE TITLE
Preparing UI visualization of the front page

### ISSUE THREAD

**Issue by mtusnio** [mhudziak/amsi#21]
Story #20

We need a layout that will contain a content frame, a menu, and a link to the login page.

**Comment by waclawjacek** [comment]
How's this going?

**Comment by darekf77** [comment]
It will be today

**Comment by waclawjacek** [comment]
Okay, ping me via @waclawjacek when it's done please. :)

**Comment by waclawjacek** [comment]
Any progress on this?
