### ISSUE TITLE
Implementation of the groups panel in admin UI

### ISSUE THREAD

**Issue by mtusnio** [mhudziak/amsi#28]
Story: #27 

A panel displaying group info and allowing for following functionality:

1) Create/edit a group
2) Deactivate or delete a group
3) Go to the course associated with this group
4) List all people in this group

**Comment by waclawjacek** [comment]
I want to postpone this until the courses module is done. @aniedziela, any ETA on it?

**Comment by aniedziela** [comment]
It will be today in the evening

**Comment by waclawjacek** [comment]
:+1:

**Comment by waclawjacek** [comment]
"List all people in this group" is waiting until the ability to register to groups is available.
