### ISSUE TITLE
Creating a login view on the main page and a controller

### ISSUE THREAD

**Issue by mtusnio** [mhudziak/amsi#30]
Story: #29

**Comment by mhudziak** [comment]
Merged with an admin login panel.

**Comment by waclawjacek** [comment]
Do we want a separate header and footer for the login screen? Or maybe should we use the same layout that we use for all the other student-oriented pages?

**Comment by mtusnio** [comment]
I'd say we should just embed the login screen in our usual headers/footers, or just add a small dropdown menu with login options if that's not too much work.
