### ISSUE TITLE
PANEL ADMINISTRACYJNY - obcinanie nazw kursów do 500 znaków bez ostrzeżenia

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#39]
Obecnie akceptowane są przez panel nazwy kursów dłuższe niż 500 znaków.
Wygląda na to że znaki o pozycjach dalszych niż 500 są tracone, gdyż po wejściu w widok danego kursu długość łańcucha w polu nazwa kursu wynosi 500 znaków.

Sugerowane jest wyświetlenie ostrzeżenia, że wprowadzany łańcuch znakowy jest zbyt długi, gdy wprowadzono ponad 500 znaków do pola "nazwa kursu" i uniemożliwienie przyjęcia takiej nazwy przez system.

**Comment by waclawjacek** [comment]
Rozwiązanie jest w sekcji "Rule Reference" rozdziału "Form Validation" user guide CodeIgnitera.
