### ISSUE TITLE
PANEL ADMINSTRATRACYJNY - Możliwe wprowadzenie tej samej nazwy dla kilku kursów

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#40]
Możliwe jest wprowadzenie wielokrotne tej samej nazwy kusru w formularzu dodawania kursu.

**Comment by waclawjacek** [comment]
Myślę, że powinniśmy na to pozwolić, bo np. dwa kierunki studiów mogą mieć analizę matematyczną, ale z innym programem. Co sądzicie?

**Comment by aniedziela** [comment]
Tak, podobnie jest w usosie. Przedmioty maja te sama nazwe,ale inne ID i naleza do roznych programow.
