### ISSUE TITLE
PANEL ADMINISTRACYJNY - próba dodania programu studiów skutkuje błędem bazy danych

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#42]
W formularzu do dowania programu studiów wpisano nazwę 'Fajny program studiów', w opisie zaś 'Bardzo ciekawy i interesujący program.'. 
Po kliknięciu na "Dodaj program" przekierowanie na stonę z komunikatem o błędzie:

Wystąpił błąd bazy danych.

Error Number: 1054

Unknown column 'active' in 'field list'

INSERT INTO `programs` (`name`, `description`, `active`) VALUES ('Fajny program studiów', 'Bardzo ciekawy i interesujący program.', 1)

Filename: /home/amsi/amsi/models/program_model.php

Line Number: 39

**Comment by waclawjacek** [comment]
Wykonaj sobie na bazie danych plik sql/01-cośtam.sql.

**Comment by studentuj** [comment]
To na serwerze developerskim

**Comment by studentuj** [comment]
Dlaczego został zamknięty? Czy zmina została wypchnięta do repo?

**Comment by waclawjacek** [comment]
To zostało już zaimplementowane, tylko masz starą strukturę bazy. Wykonaj u siebie w bazie polecenie, które jest zawarte w pliku sql/zmiany/01-programActiveStatus.sql.

**Comment by studentuj** [comment]
Jak pisałem to jest na serwerze developerskim, nie u mnie. 
Ja z tym nic nie zrobię.
