### ISSUE TITLE
Dodoawanie programu - błąd bazy danych po zatwierdzeniu formularza

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#44]
Po wypełnieniu formularza i zatwierdzeniu błąd:

Wystąpił błąd bazy danych.

Error Number: 1054

Unknown column 'active' in 'field list'

INSERT INTO `programs` (`name`, `description`, `active`) VALUES ('Świetny program', 'Ekstrawagancki!', 1)

Filename: /home/amsi/amsi/models/program_model.php

Line Number: 39

**Comment by mtusnio** [comment]
Brakuje kolumny w bazaDanych.sql, @waclawjacek moglbys na to zerknac i dodac kolumne?

**Comment by waclawjacek** [comment]
@mtusnio To jest ten sam problem, co w jednym z poprzednich ticketów, wystarczy odpalić sql/zmiany/01-cośtam.sql na bazie. Dodam. :)

**Comment by mtusnio** [comment]
Aaach, ok, rzeczywiscie. Ja po prostu odpalalem bazke na czysto jak stawialem, stad myslalem, ze powinno byc up to date. Dodaj jak mozesz, ja puszcze ten skrypcik

**Comment by studentuj** [comment]
@waclawjacek w której gałęzi jest ten plik .sql?

**Comment by waclawjacek** [comment]
@studentuj Na masterze.

**Comment by waclawjacek** [comment]
Zrobione.
