### ISSUE TITLE
Kliknięcie w napis "Projekt AMSI Panel administracyjny" przenosi na stronę "404 :

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#46]
Mowa o napisie w górnej listwie ze strony 
/amsi/admin/courses
jest ona linkiem do strony
http://cryptomaze-chariton.strangled.net/amsi/admin/index.html
jednak system nie znajduje takiej strony i zgłasza błąd 404.

**Comment by mtusnio** [comment]
U mnie dziala, moglbys sprobowac potwierdzic, czy rzeczywiscie jest problem?

**Comment by mtusnio** [comment]
Powinno juz dzialac, chyba jakiegos widoku brakowalo, a w miedzyczasie zostal wrzucony.
