### ISSUE TITLE
Nie wyświetla programów - pozycja "Programy" ze strony głównej dla niezalogowanych

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#47]
W bazie są 2 programy jeden jest aktywny drugi nieaktywny - niezalogowany użytkownik ma w menu dostępną opcję "Programy", lecz po wejściu na stonę "Programs" nie wyświetla sie w ogóle lista dostępnych programów.

**Comment by mtusnio** [comment]
Modul jeszcze nie jest zaimplementowany, #34 jeszcze jest otwarty. :)
