### ISSUE TITLE
Dodać wyświetlanie informacji z jakiego adresu się zalogowano.

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#48]
W chwili obecnej nie wyświetla się nigdzie nazwa użytkownika.
Proponuję dodać obok przycisku "wyloguj" wyświetlanie nazwy konta email zalogowanej osoby.
Obecnie tego nie ma i nie wiadomo z jakiego konta się zalogowano.

**Comment by mtusnio** [comment]
Done, w prawdzie trzeba ladowac model ion_auth_users i bezposrednio z widoku sie do niego dobierac, ale lepsze to niz nic. ;) c7a8
