### ISSUE TITLE
Can't delete courses assigned to programs

### ISSUE THREAD

**Issue by waclawjacek** [mhudziak/amsi#49]
Cannot delete or update a parent row: a foreign key constraint fails (`amsi_system_studia`.`program_courses`, CONSTRAINT `program_couses_course_id` FOREIGN KEY (`course_id`) REFERENCES `courses` (`course_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by mhudziak** [comment]
Fixed
