### ISSUE TITLE
Can't add a course without a description

### ISSUE THREAD

**Issue by waclawjacek** [mhudziak/amsi#50]
... but I guess you should be able to. WDYT?

**Comment by mtusnio** [comment]
Hmmm... works as designed? ;)

**Comment by waclawjacek** [comment]
Should every course have a description though?

**Comment by mtusnio** [comment]
I'd leave it as it is, although it'd be best to make sure there's some info about that if a user tries to add a course without any description.

**Comment by waclawjacek** [comment]
I agree, there should be some errors displayed if the form doesn't pass validatoin.

**Comment by aniedziela** [comment]
Added info about required fields in commit 1e28
