### ISSUE TITLE
Dodaj grupę zajęciową - brak weryfikacji poprawności danych - błąd bazy danych

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#51]
Po wprowadzeniu łańcucha znakowego w polu numer grupy i zatwierdzeniu formularz przenosi na strone informującą o błędzie bazy danych:

Coś jest nie tak ze skryptem bazy danych ( testowane za serwerze developerskim @mtusnio )

Wystąpił błąd bazy danych.

Error Number: 1054

Unknown column 'active' in 'field list'

INSERT INTO `course_groups` (`group_number`, `group_type`, `course_id`, `active`) VALUES ('Grupa wspaniałego prowadzącego', '0', '17', 1)

Filename: /home/amsi/amsi/models/course_group_model.php

Line Number: 39

Sugerowałbym dodanie jakiejś formy weryfikacji danych wejściowych

**Comment by mtusnio** [comment]
Nie ma w sqlu active dla grup. @waclawjacek  Dodac, czy to blad w kodzie?

**Comment by studentuj** [comment]
@waclawjacek co o tym sądzisz?

**Comment by waclawjacek** [comment]
Dodać. :) int(1) not null
29 sty 2015 18:35 "mtusnio" <notifications@github.com> napisał(a):

**Comment by studentuj** [comment]
Teraz zostało dodać sprawdzanie typu danych

Wystąpił błąd bazy danych.

Error Number: 1062

Duplicate entry '0-17' for key 'PRIMARY'

INSERT INTO `course_groups` (`group_number`, `group_type`, `course_id`, `active`) VALUES ('ziemniaki', '1', '17', 1)

Filename: /home/amsi/amsi/models/course_group_model.php

Line Number: 39

**Comment by mtusnio** [comment]
Dodalem Cie, @waclawjacek , bo w zasadzie najlepiej ogarniasz ten modul.

**Comment by studentuj** [comment]
Teraz na developerskim serwerze mam przy próbie dodania grupy

Wystąpił błąd bazy danych.

Error Number: 1062

Duplicate entry '0-1' for key 'PRIMARY'

INSERT INTO `course_groups` (`group_number`, `group_type`, `course_id`, `active`) VALUES ('2', '0', '1', 1)

Filename: /home/amsi/amsi/models/course_group_model.php

Line Number: 39

**Comment by waclawjacek** [comment]
To jest nadal ten sam problem, musimy poczekać, aż @mtusnio zaktualizuje bazę.

**Comment by mtusnio** [comment]
Done.
