### ISSUE TITLE
Zawieszenie aktywności użytkownika nie prowadzi do zmiany wyświetlanego statusu

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#52]
Status pozostaje jako "Aktywna"

**Comment by studentuj** [comment]
Ponadto dalej użytkownik może się zalogować

**Comment by mtusnio** [comment]
Investigating.

**Comment by mtusnio** [comment]
Fixed in 1eb6

**Comment by studentuj** [comment]
@mtusnio 
Po próbie logowania wyświetla się komunikat w formularzu ( w tym samym miejscu gdzie wyświetliłby się komunikat o nieprawidłowych danych do logwania )  wiadomość
>##login_unsuccessful_not_active##
Trzeba by to przetłumaczyć.

**Comment by mtusnio** [comment]
Fixed in 097b.
