### ISSUE TITLE
Można się zarejestrować na wszystkie grupy

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#54]
Jeśli się odpowiednio szybko przeklika wszystkie "Zarejestruj się".
@mtusnio  - o tym rozmawialiśmy

**Comment by mtusnio** [comment]
Investigating.

**Comment by mtusnio** [comment]
Workaround zrobiony.

**Comment by studentuj** [comment]
Jednak nie.

**Comment by mtusnio** [comment]
Na razie zamykamy jako wontfix. :)
