### ISSUE TITLE
Dodawanie nowego użytkownika - brak ostrzeżenia 

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#55]
Po wprowadzeniu w pola imię, nazwisko długiego łańcuchaznaków, zostaje ono póżniej przycięte do pewnej określonej długości. Brak ostrzeżenia o tym fakcie.

**Comment by waclawjacek** [comment]
Teraz powinno być dobrze, @studentuj, sprawdź proszę.

**Comment by studentuj** [comment]
@waclawjacek 
Nie stwierdziłem aby coś się zmieniło na serwerze developerskim
wprowadź takie łańcuchy jako imię i nazwisko:
qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890-=!@#$%^&*()_+

**Comment by studentuj** [comment]
Działa. Zamykam.
