### ISSUE TITLE
Dodawanie nowego kursu - przekierowanie na pustą stronę po zatwierdzeniu

### ISSUE THREAD

**Issue by studentuj** [mhudziak/amsi#57]
Po wprowadzeniu nazwy i opisu kursu i nie wybraniu prowadzącego ( w danym przypadku lista dostępnych prowadzących i tak jest pusta ) system przenosi na pustą stronę
amsi/admin/courses/add

**Comment by studentuj** [comment]
Kurs wygląda na to został dodany prawidłowo.

**Comment by mtusnio** [comment]
Mozesz dokladnie podac, co wpisujesz etc. i potwierdzic, ze nie dziala? Bo nie jestem w stanie zreplikowac.

**Comment by studentuj** [comment]
Przepraszam, to chyba była wina ustawień przeglądarki - blokowanie przekierowań. Bo teraz dziła. Zamykam.
